define(function(){
	return {
		'ZN': {
			"lang_refrigeratorTemperature": "冷藏室温度",
                  "lang_refrigeratorTemperature_short": "冷藏室",
                  "lang_freezerTemperature": "冷冻室温度",
                  "lang_freezerTemperature_short": "冷冻室",
                  "lang_quickRefrigeratingMode": "速冷",
                  "lang_quickRefrigeratingMode_status": "速冷模式运行中",
                  "lang_quickFreezingMode": "速冻",
                  "lang_quickFreezingMode_status": "速冻模式运行中",
                  "lang_holidayMode": "假日",
                  "lang_holidayMode_status": "假日模式运行中",
                  "lang_freshMode": "珍品",
                  "lang_freshMode_status": "珍品模式运行中",
                  "lang_icemakeMode": "制冰",
                  "lang_icemakeMode_status": "制冰",
                  "lang_intelligenceMode": "智能",
                  "lang_intelligenceMode_status": "智能模式运行中",
                  "lang_quickRefrigeratingMode_quickFreezingMode_status": "速冷、速冻模式运行中",
                  "lang_quickFreezingMode_holidayMode_status": "速冻、假日模式运行中",
                  "lang_runningStatusTitle": "冰箱运行状态",
                  "lang_temperatureTitle": "点击调整温度，可以看见实时温度",
                  "lang_modeSeeting": "选择运行模式",
                  "lang_buttonText": "了解了",
                  "alarms": {
                  	"lang_recived": "发现",
                  	"lang_andsoon": "等",
                        "lang_alarmInfo": "个警报信息",
                  	"lang_moreinfo": "查看详情",
                        "lang_alarmDescribe": "、故障描述:",

                        "lang_alarmInformation": "报警信息",
                        "lang_find": "发现",
                        "lang_resolveText": "处报警信息，请您及时排除问题",

                  	// 
                  	"envTempSensorErr": "环境温度传感器故障",
                  	"refrigeratorSensorErr": "冷藏室传感器故障",
                  	"refrigeratorDefrostingSensorErr": "冷藏化霜传感器故障",
                  	"freezerSensorErr": "冷冻室传感器故障",
                  	"vtRoomSensorErr": "变温室传感器故障",
                  	"freezerDefrostingSensorErr": "冷冻化霜传感器故障",
                  	"ctrBoardCommErr": "显示板与主板通讯故障",
                  	"freezerFanErr": "冷冻室风机故障",
                  	"coolingFanErr": "冷却风机故障",
                  	"freezerDefrostingErr": "冷冻化霜故障",
                  	"humiditySensorErr": "湿度传感器故障",
                  	"fineSensor1Err": "精控传感器1故障",
                  	"fineSensor2Err": "精控传感器2故障",
                  	"fineSensor3Err": "精控传感器3故障",
                  	"refrigeratorDefrostingErr": "冷藏化霜故障",
                  	"refrigeratorFanErr": "冷藏室风机故障",
                  	"refrigeratorDoorAlarm": "冷藏室1门开关报警",
                  	"refrigerator2DoorAlarm": "冷藏室2门开关报警",
                  	"freezerDoorAlarm": "冷冻室1门开关报警",
                  	"freezer2DoorAlarm": "冷冻室2门开关报警",
                  },
                  "deviceInfo": {
                        "lang_deviceInfo": "产品信息",
                        "lang_deviceName": "设备名称",
                        "lang_deviceEdit": "编辑设备",
                        "lang_deviceButton": "确定",
                  },
                  "lang_deviceStatus": "WIFI: ",
                  "lang_wifiStatus_on": "online",
                  "lang_wifiStatus_off": "offline",
                  "lang_maxTem": "最高温度为",
                  "lang_cannotHigh": "℃，不能再高了",
                  "lang_minTem": "最低温度为",
                  "lang_cannotLow": "℃，不能再低了"
		},
		'EN': {
			"lang_refrigeratorTemperature": "REF.temperature",
			"lang_refrigeratorTemperature_short": "REF.",
                  "lang_freezerTemperature": "FRZ.temperature",
                  "lang_freezerTemperature_short": "FRZ.",
                  "lang_quickRefrigeratingMode": "Super-Cool",
                  "lang_quickRefrigeratingMode_status": "Super-Cool is running",
                  "lang_quickFreezingMode": "Super-Frz.",
                  "lang_quickFreezingMode_status": "Super-Frz. is running",
                  "lang_holidayMode": "Holiday",
                  "lang_holidayMode_status": "Holiday is running",
                  "lang_intelligenceMode": "Fuzzy",
                  "lang_intelligenceMode_status": "Fuzzy is running",
                  "lang_quickRefrigeratingMode_quickFreezingMode_status": "Super-Cool & Super-Frz. are running",
                  "lang_quickFreezingMode_holidayMode_status": "Super-Frz. & Holiday are running",
                  "lang_runningStatusTitle": "Refrigerator running state",
                  "lang_temperatureTitle": "Click adjust temperature, you can view the real-tiem temperature",
                  "lang_modeSeeting": "mode tuning",
                  "lang_buttonText": "OK",
                  "alarms": {
                  	"lang_recived": "recived",
                  	"lang_andsoon": "",
                  	"lang_alarmInfo": "alarms info",
                        "lang_moreinfo": "click for more",
                        "lang_alarmDescribe": ". alarm detail:",

                        "lang_alarmInformation": "Alarm information",
                        "lang_find": "Find",
                        "lang_resolveText": "alarm info, Please remove the problem in time",

                  	// 
                  	"envTempSensorErr": "Ambient temperature sensor fault",
                  	"refrigeratorSensorErr": "Freezer sensor fault",
                  	"refrigeratorDefrostingSensorErr": "Cold frost sensor fault",
                  	"freezerSensorErr": "Freezing chamber sensor failure",
                  	"vtRoomSensorErr": "Greenhouse sensor failure",
                  	"freezerDefrostingSensorErr": "Frost sensor failure",
                  	"ctrBoardCommErr": "Display board and motherboard communication failure",
                  	"freezerFanErr": "Refrigerating room fan failure",
                  	"coolingFanErr": "Cooling fan failure",
                  	"freezerDefrostingErr": "Frost failure",
                  	"humiditySensorErr": "Humidity sensor failure",
                  	"fineSensor1Err": "Precision sensor 1 fault",
                  	"fineSensor2Err": "Precision sensor 2 fault",
                  	"fineSensor3Err": "Precision sensor 3 fault",
                  	"refrigeratorDefrostingErr": "Frost failure",
                  	"refrigeratorFanErr": "Cold room fan failure",
                  	"refrigeratorDoorAlarm": "Safe 1 door switch alarm",
                  	"refrigerator2DoorAlarm": "Safe 2 door switch alarm",
                  	"freezerDoorAlarm": "Freezing room 1 door switch alarm",
                  	"freezer2DoorAlarm": "Freezing room 2 door switch alarm",
                  },
                  "deviceInfo": {
                        "lang_deviceInfo": "device info",
                        "lang_deviceName": "device name",
                        "lang_deviceEdit": "device edit",
                        "lang_deviceButton": "OK",
                  },
                  "lang_deviceStatus": "WIFI: ",
                  "lang_wifiStatus_on": "online",
                  "lang_wifiStatus_off": "offline",
                  "lang_maxTem": "The maximum temperature is",
                  "lang_cannotHigh": "℃, can not be high",
                  "lang_minTem": "The minimum temperature is",
                  "lang_cannotLow": "℃, can not be lower"
		},
		'DE': {
			"lang_refrigeratorTemperature": "deasdfasdf",
            "lang_freezerTemperature": "deasdffeeeeeeee"
		}
	};
});